"""Add indexes for optimization

Revision ID: 27eb76c0e996
Revises: 113551ccf54d
Create Date: 2026-02-16 18:15:31.903005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27eb76c0e996'
down_revision: Union[str, Sequence[str], None] = '113551ccf54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_budget_user_month_year', 'budgets', ['user_id', 'month', 'year'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.create_index(op.f('ix_expenses_is_deleted'), 'expenses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_is_deleted'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index('ix_budget_user_month_year', table_name='budgets')
    # ### end Alembic commands ###
