"""enhance_categories

Revision ID: 34910275cc25
Revises: 4f4eaea9a679
Create Date: 2026-02-18 15:55:05.553048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34910275cc25'
down_revision: Union[str, Sequence[str], None] = '4f4eaea9a679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('type', sa.String(), nullable=True))
    op.execute("UPDATE categories SET type = 'expense'")
    op.alter_column('categories', 'type', nullable=False)
    
    op.add_column('incomes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incomes', 'categories', ['category_id'], ['id'])
    
    # Data Migration: Create categories from income sources
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    
    # We need to reflect the tables to work with them
    metadata = sa.MetaData()
    metadata.reflect(bind=bind)
    incomes_table = metadata.tables['incomes']
    categories_table = metadata.tables['categories']
    users_table = metadata.tables['users']
    
    # Get all incomes
    incomes = session.execute(sa.select(incomes_table)).fetchall()
    
    # Process each income to link/create category
    for income in incomes:
        source = income.source
        user_id = income.user_id
        
        # Check if category exists for this user and source (as 'income' type)
        # Note: We query directly using SQL to be safe
        existing_cat = session.execute(
            sa.select(categories_table).where(
                categories_table.c.name == source,
                categories_table.c.user_id == user_id,
                categories_table.c.type == 'income'
            )
        ).first()
        
        cat_id = None
        if existing_cat:
            cat_id = existing_cat.id
        else:
            # Create new category
            result = session.execute(
                categories_table.insert().values(
                    name=source,
                    user_id=user_id,
                    type='income'
                )
            )
            cat_id = result.inserted_primary_key[0]
            
        # Update income with category_id
        session.execute(
            incomes_table.update().where(
                incomes_table.c.id == income.id
            ).values(category_id=cat_id)
        )
            
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_column('incomes', 'category_id')
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###
