"""custom_auth_migration

Revision ID: 8d28391401b2
Revises: 34910275cc25
Create Date: 2026-02-20 18:09:19.099516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d28391401b2'
down_revision: Union[str, Sequence[str], None] = '34910275cc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('budgets', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_budget_user_month_year'), 'budgets', type_='unique')
    op.create_unique_constraint('uq_budget_user_month_year_category', 'budgets', ['user_id', 'month', 'year', 'category_id'])
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'])
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_constraint('uq_budget_user_month_year_category', 'budgets', type_='unique')
    op.create_unique_constraint(op.f('uq_budget_user_month_year'), 'budgets', ['user_id', 'month', 'year'], postgresql_nulls_not_distinct=False)
    op.drop_column('budgets', 'category_id')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
