"""Update category uniqueness

Revision ID: d1f2fb7c2d36
Revises: c1a2b3d4e5f6
Create Date: 2026-02-21 17:49:00.987377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f2fb7c2d36'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_category_name_user'), 'categories', type_='unique')
    op.create_unique_constraint('uq_category_name_type_user', 'categories', ['name', 'type', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_name_type_user', 'categories', type_='unique')
    op.create_unique_constraint(op.f('uq_category_name_user'), 'categories', ['name', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
